# Generated by Django 4.2.6 on 2023-10-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_author_remove_book_content_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
