# Generated by Django 4.2.6 on 2023-10-21 16:36

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "books.json")

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_isbn'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data)
    ]
