# Generated by Django 4.1.4 on 2023-10-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_userbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='authors',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='cover_img',
            field=models.URLField(blank=True, default='https://static.thenounproject.com/png/3674271-200.png', null=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='isbn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='pub_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='publisher',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
