# Generated by Django 4.1.4 on 2023-10-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_userbook_authors_alter_userbook_cover_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='cover_img',
            field=models.URLField(blank=True, default='https://static.thenounproject.com/png/3674271-200.png'),
        ),
    ]
