# Generated by Django 4.2.5 on 2023-10-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('pub_year', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_img', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ('title',),
            },
        ),
    ]
