# Generated by Django 4.2.5 on 2023-10-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0003_bulletin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='user',
        ),
    ]
